name: "Ying's Blog"
permalink: /:title
# permalink: /:categories/:year/:month/:day/:title

author: "yingshin"
atom-baseurl: "http://izualzhy.cn"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Books
    class: fa fa-book
    href: /books.html
  - title: Paper_Slides
    class: fa fa-newspaper-o
    href: /paper_slides.markdown
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

